name: "Update Description Using README"
description: "GitHub Action to update repository's description using README."
author: "rtvu"

branding:
  icon: "book-open"
  color: "gray-dark"

inputs:
  repository:
    description: "Repository"
    required: true
  readme:
    description: "Path to README"
    required: false
    default: "README.md"
  update:
    description: "Update repository"
    required: false
    default: true
  token:
    description: "GitHub token"
    required: true

outputs:
  description:
    description: "README's description"
    value: ${{ steps.get-description.outputs.description }}

runs:
  using: "composite"
  steps:
    -
      name: Get description
      id: get-description
      shell: python3 -u {0} ${{ inputs.readme }}
      run: |
        import argparse
        import os

        def get_description(readme_path):
            description = ""
            with open(readme_path, "r") as readme:
                for line in readme:
                    line = line.strip()
                    if len(line) > 0 and line[0] != "#":
                        description = line
                        break
            output_path = os.getenv("GITHUB_OUTPUT")
            with open(output_path, "a") as output:
                output.write(f"description={description}")

        def main():
            parser = argparse.ArgumentParser()
            parser.add_argument("readme_path", nargs="?", type=str, help="Path to README", default="README.md")
            args = parser.parse_args()
            get_description(readme_path=args.readme_path)

        if __name__ == "__main__":
            main()
    -
      name: Update repository
      if: ${{ inputs.update }} == "true"
      shell: bash
      run: |
        gh api \
          --method PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ inputs.repository }} \
          -f description="${{ steps.get-description.outputs.description }}"
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
