name: "Update Repository Description"

on:
  push:
    branches:
      - "development"
    paths:
      - "README.md"

jobs:
  update-repository-description:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Update repository description
        uses: rtvu/update-description-using-readme@v1.0.2
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.REPOSITORY_PAT }}
